### PR TITLE
Graceful errors

### PR DESCRIPTION
**Pull request by Bart6114**

### CODE REVIEW

**Comment by Bart6114** [comment]
Can we update this message as well to notify the user more explicitly of the existence of the `-s` flag?

```
❯ cheek ui
Error connecting with cheek server: Error connecting to cheek server and no schedule file specified: Get "http://localhost:8081/schedule": dial tcp [::1]:8081: connect: connection refused
```

**Comment by Bart6114** [comment]
Screenshot 2021-12-17 at 09 38 41

What if we use lower-right side to show errors? If need be we drop the hex thing, with pain in my heart though 💔 

Are there actually errors that need user input at this stage? E.g. a "scheduler not available, can't refresh state" is ok to just notify the user about.

**Comment by frederikdesmedt** [comment]
Yes, good idea. I was also thinking about handling panics that have a stacktrace, but there we might as well just kill the TUI and print the error after bubbletea has shut down... And we'll make the error messages reported in the TUI more user-friendly then, like the one you mentioned. What if the user sees: "scheduler not available, can't refresh state" and they want to learn more? I'm thinking stacktraces/errors raised by functions. Maybe we can write this to a `.log`? Because just `Print`ing it won't show it, given that bubbletea replaces stdout

**Comment by Bart6114** [comment]
> Maybe we can write this to a `.log`?

Perhaps we should just also show the core scheduler logs in the TUI? They already exist under `cheek.core.json`.. And from an error you can do something like "press (l) to show logs" and just open the core logs.

**Pull request merged**
